// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function mapApiUserToProfile(apiUser: any) {
  return {
    id: apiUser.id,
    user_id: apiUser.id,
    full_name: apiUser.name,
    username: apiUser.username,
    profile_picture: apiUser.avatar,
    cover_photo: apiUser.cover_photo,
    email: apiUser.email,
    phone_number: apiUser.phone || apiUser.whatsapp_number,
    location: [apiUser.city, apiUser.state, apiUser.country]
      .filter(Boolean)
      .join(", "),
    address: "",
    website_url: apiUser.website_url,
    headline: apiUser.headline,
    bio: apiUser.bio,
    company_name: apiUser.company_name,
    job_title: apiUser.job_title,
    industry: apiUser.industry,
    skills: apiUser.skills || [],
    linkedin_url: apiUser.linkedin_url,
    instagram_url: apiUser.instagram_url,
    facebook_url: apiUser.facebook_url,
    twitter_url: apiUser.twitter_url,
    youtube_url: apiUser.youtube_url,
    github_url: apiUser.github_url,
    behance_url: apiUser.behance_url,
    dribbble_url: apiUser.dribbble_url,
    pinterest_url: apiUser.pinterest_url,
    threads_url: apiUser.threads_url,
    tiktok_url: apiUser.tiktok_url,
    snapchat_url: apiUser.snapchat_url,
    custom_links: apiUser.custom_links || [],
    vcard_url: apiUser.vcard_url,
    pdf_resume_url: apiUser.pdf_resume_url,
    gallery: apiUser.gallery || [],
    profile_type: apiUser.profile_type,
    is_public: apiUser.is_public,
    allow_contact_form: apiUser.allow_contact_form,
    dark_mode_enabled: apiUser.dark_mode_enabled,
    custom_theme_color: apiUser.custom_theme_color || "#04cefa",
    qr_code_url: apiUser.qr_code_url,
    seo_title: apiUser.seo_title,
    seo_description: apiUser.seo_description,
    views_count: apiUser.views_count || 0,
    last_tapped_at: apiUser.last_tapped_at,
    created_at: apiUser.created_at,
    updated_at: apiUser.updated_at,
  };
}
